on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

permissions:
  contents: write

env:
  version: m132-9b3c42e2f9-3

jobs:
  linux-arm64:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        build_type: [ Debug, Release ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        name: Assemble
        id: assemble
        with:
            image: arm64v8/ubuntu:20.04
            # Mount checkout directory as /checkout in the container
            options: -v ${{ github.workspace }}:/checkout -e BUILD_TYPE=${{ matrix.build_type }} -e BUILD_VERSION=${{ env.version }} 
            # The shell to run commands with in the container
            shell: /bin/bash
            run: |
              cd /checkout
              /bin/bash script/prepare_linux_arm.sh
              python3 script/checkout.py --version ${BUILD_VERSION}
              python3 script/build.py --build-type ${BUILD_TYPE}
              python3 script/archive.py --version ${BUILD_VERSION} --build-type ${BUILD_TYPE}
      - uses: actions/upload-artifact@v4
        if: ${{ github.event.inputs.skip_release != 'true' && github.ref == 'refs/heads/main' }}
        with:
            name: Skia-${{ env.version }}-linux-${{ matrix.build_type }}-arm64.zip
            path: '*.zip'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: python3 script/release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }} --target linux --machine arm64
        if: ${{ github.event.inputs.skip_release != 'true' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
